list_of_strings = ["a", "bc", "def"]
print("list_of_strings:", list_of_strings)
print()
print("element 0 of list_of_strings:", list_of_strings[0])
print("element 1 of list_of_strings:", list_of_strings[1])
print("element 2 of list_of_strings:", list_of_strings[2])
print()
list_of_any = ["a", 1, True, None, ["qwe", 543], 3.5]
print("list_of_any ", list_of_any)
print()
print("Длина списка list_of_any:", len(list_of_any))
print("Цикл for, функция type(), __name__ - имя типа ")
# print("object type:", type(list_of_any[0])) вывод на печать нулевого элемента списка
# print("object type:", type(list_of_any[1])) вывод на печать первого элемента списка
# print("object type:", type(list_of_any[2]))
# print("object type:", type(list_of_any[3]))
# print("object type:", type(list_of_any[4]))
# print("object type:", type(list_of_any[5]))
for item in list_of_any:
    print("Тип,", "элемента", type(item).__name__)
print()
for index, item in enumerate(list_of_any):
    print(f"Тип элемента #{index} - {type(item).__name__}")
print()
print("Добавление элемента .append")    
list_of_strings.append("gehi")
print(list_of_strings)
print()
another_list_of_strings = list_of_strings
print(list_of_strings)
print(another_list_of_strings)
print()
#присвоение 0-му элементу списка - нового значения
list_of_strings[0] = "aaa"
another_list_of_strings.append("qwe")
print(list_of_strings)
print(another_list_of_strings)
print(list_of_strings == another_list_of_strings)
print(list_of_strings is another_list_of_strings)
new_list_of_strings = list(list_of_strings)
print(new_list_of_strings)
print(list_of_strings)

print(new_list_of_strings.pop())
print(new_list_of_strings.pop(0))
print(list_of_strings)
print(new_list_of_strings)
list_of_strings.append("wasd")
print("list_of_strings:", list_of_strings)
print()
one_more_list_of_strings = list(new_list_of_strings)
print("one_more_list_of_strings:",one_more_list_of_strings)
print("type: ", type(one_more_list_of_strings))
print()
print("new_list_of_strings:",new_list_of_strings)
print()
print("list_of_strings:", list_of_strings)
print("type: ", type(list_of_strings).__name__)
print("list_of_strings[0:2]:",list_of_strings[0:2])
print("list_of_strings[2:3]:",list_of_strings[2:3])
print("list_of_strings[1:4]:",list_of_strings[1:4])
print("list_of_strings[:34]:",list_of_strings[:34])
print("list_of_strings[2:]:",list_of_strings[2:])
print("list_of_strings[:]:",list_of_strings[:])
print("list_of_strings[:] == list_of_strings? - ",list_of_strings[:] == list_of_strings)
print("list_of_strings[:] is list_of_strings? - ",list_of_strings[:] is list_of_strings)

tuple_of_strings = ("123", "456")
print("tuple_of_strings: ", tuple_of_strings)
print('tuple of strings == ("123", "456")? - ', tuple_of_strings == ("123", "456"))
print('tuple of strings == list(tuple_of_strings)? - ', tuple_of_strings == list(tuple_of_strings))
print('tuple([123, 456]) == (123, 456) - ',  tuple([123, 456]) == (123, 456))
set_of_numbers = {1, 2, 3}
print('set_of_numbers = {1, 2, 3} -', set_of_numbers)
empty_set = set()
print(empty_set)
set_of_numbers.add(0)
print('Выполнение set_of_numbers.add(0) result:', set_of_numbers)
print()
set_of_numbers.add(42)
set_of_numbers.add(15)
print('Выполнение подряд:\n1)set_of_numbers.add(42)\n2)set_of_numbers.add(15)\nрезультат:', set_of_numbers)
print()
print("{1, 2} | {2, 3} = ", {1, 2} | {2, 3})
print()
print("{1, 2} ^ {2, 3} = ", {1, 2} ^ {2, 3})
print()
print("{1, 2} & {2, 3} = ", {1, 2} & {2, 3})
print()
print("{1, 2} - {2, 3} = ", {1, 2} - {2, 3})
print()
print("{2, 3} - {1, 2} = ", {2, 3} - {1, 2})
print()
print("{1, 2, 5} - {5} = ", {1, 2, 5} - {5})
print()
print("{1, 2} < {0, 1, 2, 3} = ", {1, 2} < {0, 1, 2, 3})
print()
print("{1, 2, 4} < {0, 1, 2, 3} = ", {1, 2, 4} < {0, 1, 2, 3})
print()
dict_of_numbers = {
    1: "one",
    2: "two",
    3: "three",
}
print(dict_of_numbers)
a, b = (1, 2)
c, d = 1, 2
print(a, b, c, d)
print(dict_of_numbers[1])
dict_of_numbers["4"] = "four"
print(dict_of_numbers)
dict_of_numbers[4] = "four"
print(dict_of_numbers)
print(4 in dict_of_numbers)
print('4' in dict_of_numbers)
print('5' in dict_of_numbers)